json.id task_request.id
json.user_first_name task_request.user.first_name
json.user_last_name task_request.user.last_name
json.task task_request.task.title
json.task_location task_request.address
json.task_description task_request.task.description
json.tasker task_request.tasker.name
json.tasker_email task_request.tasker.email
json.address task_request.address
json.day task_request.date
json.task_id task_request.task_id
json.rate task_request.tasker.price
json.hours task_request.hours
